// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderManagement.Api.Data;

#nullable disable

namespace OrderManagement.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250608120000_AddD100Module")]
partial class AddD100Module
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("OrderManagement.Api.Models.Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CustomerName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Notes")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<decimal>("Price")
                    .HasPrecision(18, 2)
                    .HasColumnType("numeric(18,2)");

                b.Property<string>("Product")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<int>("Quantity")
                    .HasColumnType("integer");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("Id");

                b.HasIndex("CreatedAt");

                b.HasIndex("Status");

                b.ToTable("Orders");
            });

        modelBuilder.Entity("OrderManagement.Api.Models.CompanyProfile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Adresa")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<string>("Cui")
                    .IsRequired()
                    .HasMaxLength(13)
                    .HasColumnType("character varying(13)");

                b.Property<string>("Denumire")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Email")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("FunctieDeclar")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("NumeDeclar")
                    .IsRequired()
                    .HasMaxLength(75)
                    .HasColumnType("character varying(75)");

                b.Property<string>("PrenumeDeclar")
                    .IsRequired()
                    .HasMaxLength(75)
                    .HasColumnType("character varying(75)");

                b.Property<string>("Telefon")
                    .HasMaxLength(15)
                    .HasColumnType("character varying(15)");

                b.HasKey("Id");

                b.ToTable("CompanyProfiles");
            });

        modelBuilder.Entity("OrderManagement.Api.Models.D100Declaration", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("An")
                    .HasColumnType("integer");

                b.Property<string>("CodBugetar")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)");

                b.Property<string>("CodOblig")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Luna")
                    .HasColumnType("integer");

                b.Property<string>("NrEvidenta")
                    .IsRequired()
                    .HasMaxLength(23)
                    .HasColumnType("character varying(23)");

                b.Property<int>("OrderCount")
                    .HasColumnType("integer");

                b.Property<string>("PdfPath")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Scadenta")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<long>("SumaDat")
                    .HasColumnType("bigint");

                b.Property<long>("SumaDed")
                    .HasColumnType("bigint");

                b.Property<long>("SumaPlata")
                    .HasColumnType("bigint");

                b.Property<long>("SumaRest")
                    .HasColumnType("bigint");

                b.Property<decimal>("TotalSales")
                    .HasPrecision(18, 2)
                    .HasColumnType("numeric(18,2)");

                b.Property<long>("TotalPlataA")
                    .HasColumnType("bigint");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ValidationErrors")
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)");

                b.Property<string>("XmlPath")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.HasKey("Id");

                b.HasIndex("Luna", "An")
                    .IsUnique();

                b.ToTable("D100Declarations");
            });
#pragma warning restore 612, 618
    }
}
