export const d100Labels = {
  tabTitle: 'Declarația D100',
  companySection: 'Date companie',
  periodSection: 'Perioadă raportare',
  previewSection: 'Previzualizare (simulare vânzări)',
  actionsSection: 'Generare declarație',
  cui: 'CUI',
  denumire: 'Denumire',
  adresa: 'Adresă',
  telefon: 'Telefon',
  email: 'E-mail',
  numeDeclar: 'Nume declarant',
  prenumeDeclar: 'Prenume declarant',
  functieDeclar: 'Funcție declarant',
  luna: 'Luna',
  an: 'Anul',
  saveCompany: 'Salvează profil companie',
  preview: 'Previzualizare',
  generateXml: 'Generează XML',
  generatePdf: 'Generează PDF',
  downloadXml: 'Descarcă XML',
  downloadPdf: 'Descarcă PDF',
  orderCount: 'Comenzi finalizate',
  totalSales: 'Total vânzări',
  sumaDat: 'Sumă datorată (simulată)',
  totalPlataA: 'Total plată A',
  codOblig: 'Cod obligație',
  codBugetar: 'Cod bugetar',
  scadenta: 'Scadență',
  simulationNote: 'Notă simulare',
  status: 'Status declarație',
  loading: 'Se încarcă...',
  saving: 'Se salvează...',
  generating: 'Se generează...',
  noPreview: 'Selectați perioada și apăsați Previzualizare.',
  disclaimer:
    'Valorile sunt calculate din comenzile cu status Finalizată. Aceasta este o simulare pentru test tehnic, nu o declarație fiscală reală.',
  months: [
    'Ianuarie', 'Februarie', 'Martie', 'Aprilie', 'Mai', 'Iunie',
    'Iulie', 'August', 'Septembrie', 'Octombrie', 'Noiembrie', 'Decembrie',
  ],
};
