export const labels = {
  appTitle: 'Gestionare Comenzi',
  ordersTab: 'Comenzi',
  ordersTitle: 'Comenzi',
  addOrder: 'Adaugă comandă',
  editOrder: 'Editează comandă',
  newOrder: 'Comandă nouă',
  save: 'Salvează',
  cancel: 'Anulează',
  delete: 'Șterge',
  edit: 'Editează',
  actions: 'Acțiuni',
  customer: 'Client',
  product: 'Produs',
  quantity: 'Cantitate',
  price: 'Preț',
  status: 'Status',
  notes: 'Note',
  createdAt: 'Creat la',
  id: '#',
  loading: 'Se încarcă comenzile...',
  empty: 'Nu există comenzi înregistrate.',
  confirmDeleteTitle: 'Confirmare ștergere',
  confirmDeleteMessage: 'Sigur doriți să ștergeți această comandă? Această acțiune nu poate fi anulată.',
  errorLoading: 'Eroare la încărcarea comenzilor',
  errorSaving: 'Eroare la salvarea comenzii',
  errorDeleting: 'Eroare la ștergerea comenzii',
  refresh: 'Actualizează',
  retry: 'Reîncearcă',
  requiredField: 'Câmp obligatoriu',
  minQuantity: 'Cantitatea minimă este 1',
  minPrice: 'Prețul nu poate fi negativ',
  totalOrders: (count) => `${count} comenzi`,
};
